author: Wojciech Danilo
category: Data
default-extensions: [ConstraintKinds, DataKinds, DefaultSignatures, DeriveDataTypeable,
  DeriveFoldable, DeriveFunctor, DeriveGeneric, DeriveTraversable, DoAndIfThenElse,
  EmptyDataDecls, FlexibleContexts, FlexibleInstances, GeneralizedNewtypeDeriving,
  InstanceSigs, LambdaCase, MultiParamTypeClasses, OverloadedStrings, StandaloneDeriving,
  TemplateHaskell, TupleSections, TypeOperators, ViewPatterns, TypeFamilies, NoImplicitPrelude]
dependencies: [base, convert, data-construction, deepseq, lens, data-rtuple, prologue,
  data-layer, data-prop, typelevel, ghc-prim]
github: https://github.com/wdanilo/data-shell
library: {ghc-options: -Wall -O2, source-dirs: src}
license: Apache-2.0
maintainer: Wojciech Danilo <wojciech.danilo@gmail.com>
name: data-shell
stability: experimental
synopsis: Data shell is a dependent-type utility allowing wrapping any data-type into
  layers containing additional information.
version: 0.3.2
